<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate('Krenke Brinquedos'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js') ?>
    <style type="text/css">
    body {
        padding-top: 20px;
        padding-bottom: 40px;
    }

    /* Custom container */
    .container-narrow {
        margin: 0 auto;
        max-width: 700px;
    }
    .container-narrow > hr {
        margin: 30px 0;
    }

    /* Main marketing message and sign up button */
    .jumbotron {
        margin: 60px 0;
        text-align: center;
    }
    .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
    }
    .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
    }

    /* Supporting marketing content */
    .marketing {
        margin: 60px 0;
    }
    .marketing p + h4 {
        margin-top: 28px;
    }
    </style>
</head>
<body>
    <div class="container-narrow">
        <div class="masthead">
            <ul class="nav nav-pills pull-right">
                <li class="active"><a href="/application/index"><?=$this->translate('Início')?></a></li>
                <li><a href="/application/index/about"><?=$this->translate('Sobre')?></a></li>
                <li><a href="/application/index/contact"><?=$this->translate('Contato')?></a></li>
            </ul>
            <h3 class="muted"><?= $this->translate('Krenke Playgrounds')?></h3>
        </div>

        <hr>

        <?php echo $this->content; ?>

        <hr>

        <div class="footer">
            <p>&copy; Krenke Brinquedos Pedagógicos  2013</p>
        </div>

    </div> <!-- /container -->
</body>
</html>
