<div class="row-fluid marketing">
	<div class="span6">
		<h4><?=$this->translate('Fotos')?></h4>
		<p><?=$this->translate('A partir de agora nosso site contará com uma sessão de fotos atualizadas!')?></p>

		<h4><?=$this->translate('Segurança')?></h4>
		<p><?=$this->translate('O Brasil e a ABNT estão implantando normas de segurança para que seu filho brinque com maior segurança. A Krenke tem o prazer de trazer este conhecimento a nossos clientes.')?></p>
	</div>

	<div class="span6">
		<h4><?=$this->translate('Contato')?></h4>
		<p><?=$this->translate('Via telefone: (47) 3373 0693 ou email: contato@krenke.com.br')?></p>

		<h4><?=$this->translate('Onde estamos?')?></h4>
		<p><?=$this->translate('Situados na cidade de Guaramirim/SC, nosso endereço é: Rua Rodolfo Tepasse, 250 - Bairro Imigrantes.')?></p>
	</div>
</div>